FROM python:3.8

COPY app.py .

RUN true

COPY binance.py .

RUN true

COPY hitbtc.py .

RUN true

COPY ku.py .

RUN true

COPY exchange.py .

RUN true

COPY symbol.py

RUN true

COPY requirements.txt .

RUN true

RUN pip install -r requirements.txt

CMD ["python", "./app.py"]